name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            arch: amd64
          - os: macos-latest
            goos: darwin
            arch: amd64
          - os: windows-latest
            goos: windows
            arch: amd64
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Client
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.arch }}
        run: |
          cd ${{ github.workspace }}
          mkdir -p ./cmd/
          go build  -o doggie-tunnel-${GOOS}_${GOARCH}  ./cmd/root.go 
          mkdir release
          mv doggie-tunnel* release/

      - uses: actions/upload-artifact@v4
        with:
          name: release-binaries-${{ matrix.goos }}-${{ matrix.arch }}  # Unique name per architecture
          path: release/


  release:
    name: Create Release
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 新增权限声明
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          files: |
            artifacts/release-binaries/*