name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-client:
    name: Build Client
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            arch: amd64
          - os: macos-latest
            goos: darwin
            arch: amd64
          - os: windows-latest
            goos: windows
            arch: amd64
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Client
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.arch }}
        run: |
          cd ${{ github.workspace }}
          pwd  # 调试路径
          ls -al  # 查看目录结构
          mkdir -p ./cmd/
          go build  ./cmd/client.go -o doggie-tunnel-client_${GOOS}_${GOARCH} 
          mkdir release
          mv doggie-tunnel-client* release/

      - uses: actions/upload-artifact@v4
        with:
          name: client-binaries
          path: release/

  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Server
        run: |
          cd ${{ github.workspace }}
          pwd  # 调试路径
          ls -al  # 查看目录结构
          mkdir -p ./cmd/
          go build ./cmd/server.go -o doggie-tunnel-server_linux_amd64 
          mkdir release
          mv doggie-tunnel-server* release/

      - uses: actions/upload-artifact@v4
        with:
          name: server-binary
          path: release/

  release:
    name: Create Release
    needs: [build-client, build-server]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 新增权限声明
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          files: |
            artifacts/client-binaries/*
            artifacts/server-binary/*